{
  "apiVersion": "networking.k8s.io/v1",
  "kind": "NetworkPolicy",
  "metadata": {
    "name": {{ printf "%s-namespace-ingress" .Release.Name | toJson }},
    "namespace": {{ .Release.Namespace | toJson }},
    "labels": {
      "app.kubernetes.io/name": {{ .Release.Name | toJson }},
      "app.kubernetes.io/instance": {{ .Release.Name | toJson }},
      "app.kubernetes.io/part-of": "exepno-performance",
      "app.kubernetes.io/managed-by": {{ .Release.Service | toJson }}
    }
  },
  "spec": {
    "podSelector": {
      "matchLabels": {
        "app.kubernetes.io/instance": {{ .Release.Name | toJson }}
      }
    },
    "policyTypes": [
      "Ingress"
    ],
    "ingress": [
      {
        "from": [
          {
            "podSelector": {
              "matchLabels": {
                "app.kubernetes.io/instance": {{ .Release.Name | toJson }}
              }
            }
          }
        ]
      }
    ]
  }
}
