{{- if not (index .Values.persistence "model-cache" "existingClaim") }}
{
  "apiVersion": "v1",
  "kind": "PersistentVolumeClaim",
  "metadata": {
    "name": {{ printf "%s-model-cache" .Release.Name | toJson }},
    "namespace": {{ .Release.Namespace | toJson }},
    "labels": {
      "app.kubernetes.io/name": {{ .Release.Name | toJson }},
      "app.kubernetes.io/instance": {{ .Release.Name | toJson }},
      "app.kubernetes.io/part-of": "exepno-performance",
      "app.kubernetes.io/managed-by": {{ .Release.Service | toJson }}
    },
    "annotations": {
      "helm.sh/resource-policy": "keep",
      "exepno.bisees.com/storage-lifecycle": "v1"
    }
  },
  "spec": {
    "accessModes": [
      "ReadWriteOnce"
    ],
    "storageClassName": {{ index .Values "persistence" "model-cache" "storageClass" | toJson }},
    "resources": {
      "requests": {
        "storage": {{ index .Values "persistence" "model-cache" "size" | toJson }}
      }
    }
  }
}
{{- end }}
