{
  "apiVersion": "v1",
  "kind": "Service",
  "metadata": {
    "name": {{ printf "%s-frontend" .Release.Name | toJson }},
    "namespace": {{ .Release.Namespace | toJson }},
    "labels": {
      "app.kubernetes.io/name": {{ .Release.Name | toJson }},
      "app.kubernetes.io/instance": {{ .Release.Name | toJson }},
      "app.kubernetes.io/part-of": "exepno-performance",
      "app.kubernetes.io/managed-by": {{ .Release.Service | toJson }}
    }
  },
  "spec": {
    "type": "ClusterIP",
    "selector": {
      "app": "frontend",
      "app.kubernetes.io/instance": {{ .Release.Name | toJson }}
    },
    "ports": [
      {
        "port": 3000,
        "targetPort": 3000
      }
    ]
  }
}
